/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedViewedRouteImport } from './routes/_authenticated/viewed'
import { Route as AuthenticatedProxiesRouteImport } from './routes/_authenticated/proxies'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBuyRouteImport } from './routes/_authenticated/buy'
import { Route as AuthenticatedPlansDailyRouteImport } from './routes/_authenticated/plans.daily'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedViewedRoute = AuthenticatedViewedRouteImport.update({
  id: '/viewed',
  path: '/viewed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProxiesRoute = AuthenticatedProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuyRoute = AuthenticatedBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlansDailyRoute = AuthenticatedPlansDailyRouteImport.update({
  id: '/plans/daily',
  path: '/plans/daily',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buy': typeof AuthenticatedBuyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/proxies': typeof AuthenticatedProxiesRoute
  '/viewed': typeof AuthenticatedViewedRoute
  '/plans/daily': typeof AuthenticatedPlansDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buy': typeof AuthenticatedBuyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/proxies': typeof AuthenticatedProxiesRoute
  '/viewed': typeof AuthenticatedViewedRoute
  '/plans/daily': typeof AuthenticatedPlansDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/buy': typeof AuthenticatedBuyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/proxies': typeof AuthenticatedProxiesRoute
  '/_authenticated/viewed': typeof AuthenticatedViewedRoute
  '/_authenticated/plans/daily': typeof AuthenticatedPlansDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buy'
    | '/dashboard'
    | '/proxies'
    | '/viewed'
    | '/plans/daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buy'
    | '/dashboard'
    | '/proxies'
    | '/viewed'
    | '/plans/daily'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/buy'
    | '/_authenticated/dashboard'
    | '/_authenticated/proxies'
    | '/_authenticated/viewed'
    | '/_authenticated/plans/daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/viewed': {
      id: '/_authenticated/viewed'
      path: '/viewed'
      fullPath: '/viewed'
      preLoaderRoute: typeof AuthenticatedViewedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proxies': {
      id: '/_authenticated/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof AuthenticatedProxiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buy': {
      id: '/_authenticated/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof AuthenticatedBuyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans/daily': {
      id: '/_authenticated/plans/daily'
      path: '/plans/daily'
      fullPath: '/plans/daily'
      preLoaderRoute: typeof AuthenticatedPlansDailyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBuyRoute: typeof AuthenticatedBuyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProxiesRoute: typeof AuthenticatedProxiesRoute
  AuthenticatedViewedRoute: typeof AuthenticatedViewedRoute
  AuthenticatedPlansDailyRoute: typeof AuthenticatedPlansDailyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBuyRoute: AuthenticatedBuyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProxiesRoute: AuthenticatedProxiesRoute,
  AuthenticatedViewedRoute: AuthenticatedViewedRoute,
  AuthenticatedPlansDailyRoute: AuthenticatedPlansDailyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
